# Generated by Django 5.2.3 on 2025-06-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_user',
            new_name='is_public',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_municipal',
            field=models.BooleanField(default=False),
        ),
    ]
