# Generated by Django 5.2.3 on 2025-06-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools', '0003_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_google',
            field=models.BooleanField(default=False),
        ),
    ]
